### ISSUE TITLE
How to get file contents?

### ISSUE THREAD

**Issue by Tropicalista** [coldbox-modules/s3sdk#28]
How can I get file contents?

If I have a sample.txt how can I read it?

**Comment by sbleon** [comment]
Looking at the [API docs](
https://s3.amazonaws.com/apidocs.ortussolutions.com/coldbox-modules/s3sdk/4.6.0/index.html),
I don't see a method for retrieving a file. Until we have one, you can use
`getAuthenticatedURL()` to get a download URL and then use `http()` to
download the file.

https://helpx.adobe.com/coldfusion/cfml-reference/script-functions-implemented-as-cfcs/http.html

**Comment by Tropicalista** [comment]
Well I can use fileread with the getAuthenticatedURL().

I was asking because it seems something that should be integrated in the sdk.

**Comment by sbleon** [comment]
I think that would be a good addition to this library. If you'd like to
work on adding it, I'd be happy to answer questions and review your PR when
it's ready.

**Comment by Tropicalista** [comment]
At the moment I'm using something like this:
```
var accessKey = s3.getAccessKey()
var secretKey = s3.getSecretKey()
return fileRead("s3://#accessKey#:#secretKey#@" & bucketPath &  "/" & arguments.path);
```
I can make PR based on this, but it's not clear if you intend this or you want build something that completely get rid of using native functions.

Can you clarify?

**Comment by sbleon** [comment]
I think that the `FileRead()` approach may stop working sometime soon,
depending on which CFML engine you're using. I don't think this package
should use `FileRead()` because it won't work consistently across
platforms. I think our approach should use `http()` instead.

AWS deprecation status:
https://aws.amazon.com/blogs/aws/amazon-s3-update-sigv2-deprecation-period-extended-modified/
.

Older ColdFusion servers don't support SigV4 request signing.
https://brianklaas.net/aws/coldfusion/2019/06/20/End-Of-V2-Signature-Requests-For-S3.html

Lucee currently only supports the deprecated SigV2 signing mechanism for S3
requests.
https://dev.lucee.org/t/deprecation-of-s3-storage-access-june-2019/5751/14

**Comment by jordanclark** [comment]
@Tropicalista My PR #13 adds 2 methods for reading objects: getObject() and downloadObject()

**Comment by Tropicalista** [comment]
@jordanclark Many thanks, mate.
